import type { Metadata } from "next";
import { Roboto, Plus_Jakarta_Sans } from "next/font/google"; // note: Geist → GeistSans
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"], // all available weights
  style: ["normal", "italic"], // includes italics!
  display: "swap",
  variable: "--font-plus-jakarta-sans", // CSS var for Tailwind
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],     // enables italic variants
  display: "swap",
  variable: "--font-roboto",       // CSS var for Tailwind
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${plusJakartaSans.variable} ${roboto.variable}`}
    >
      <body className={`${plusJakartaSans.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}